export default {
  login: "ramesh043",
  id: 84142679,
  node_id: "MDQ6VXNlcjg0MTQyNjc5",
  avatar_url: "https://avatars.githubusercontent.com/u/84142679?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ramesh043",
  html_url: "https://github.com/ramesh043",
  followers_url: "https://api.github.com/users/ramesh043/followers",
  following_url:
    "https://api.github.com/users/ramesh043/following{/other_user}",
  gists_url: "https://api.github.com/users/ramesh043/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ramesh043/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ramesh043/subscriptions",
  organizations_url: "https://api.github.com/users/ramesh043/orgs",
  repos_url: "https://api.github.com/users/ramesh043/repos",
  events_url: "https://api.github.com/users/ramesh043/events{/privacy}",
  received_events_url: "https://api.github.com/users/ramesh043/received_events",
  type: "User",
  site_admin: false,
  name: "Rameshdev",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: true,
  bio: "I want to become a devel0per....",
  twitter_username: null,
  public_repos: 5,
  public_gists: 0,
  followers: 1,
  following: 22,
  created_at: "2021-05-13T15:24:44Z",
  updated_at: "2024-02-20T08:06:03Z",
};
